POST https://autumn-delicate-wilderness.glitch.me/v1/auth/register
Content-Type: application/json

{
    "email": "ttt@ttt.lt",
    "password": "ttt"
}

###

POST https://autumn-delicate-wilderness.glitch.me/v1/auth/login
Content-Type: application/json

{
    "email": "ttt@ttt.lt",
    "password": "ttt"

}

###
GET https://autumn-delicate-wilderness.glitch.me/v1/content/skills
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjI4LCJlbWFpbCI6InR0dEB0dHQubHQiLCJpYXQiOjE2NTAwNTM0OTh9.KVDe6RJoAqH66GI8PDb5Mtgv3Pirra1QWxdfG6smhZk

###

POST https://autumn-delicate-wilderness.glitch.me/v1/content/skills
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjI4LCJlbWFpbCI6InR0dEB0dHQubHQiLCJpYXQiOjE2NTAwNTM0OTh9.KVDe6RJoAqH66GI8PDb5Mtgv3Pirra1QWxdfG6smhZk

{
    "title": "html",
    "description": "allways good"

}