POST https://autumn-delicate-wilderness.glitch.me/v1/auth/register
Content-Type: application/json

{
    "email": "jane@dou.com",
    "password": "dou"
}

###

POST https://autumn-delicate-wilderness.glitch.me/v1/auth/login
Content-Type: application/json

{
    "email": "jane@dou.com",
    "password": "dou"

}

###
GET https://autumn-delicate-wilderness.glitch.me/v1/content/skills
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzUxLCJlbWFpbCI6ImphbmVAZG91LmNvbSIsImlhdCI6MTY1MDM1MDQzNn0.RJtZIzbnCLOLpNRYMvqIDEB71VAI2g7wzJIKRl18NGQ
###

POST https://autumn-delicate-wilderness.glitch.me/v1/content/skills
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzUxLCJlbWFpbCI6ImphbmVAZG91LmNvbSIsImlhdCI6MTY1MDM1MDQzNn0.RJtZIzbnCLOLpNRYMvqIDEB71VAI2g7wzJIKRl18NGQ
{
    "title": "html",
    "description": "allways good"

}